backend = "glx";

shadow = true;
shadow-radius = 40;
shadow-offset-x = -38;
shadow-offset-y = -30;
shadow-opacity = 0.2;
shadow-red = 0;
shadow-green = 0;
shadow-blue = 0;

inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = true;

corner-radius = 12.0;

fading = true;
fade-in-step = 0.025;
fade-out-step = 0.025;
fade-delta = 3;
no-fading-destroyed-argb = true;

vsync = true;

rounded-corners-exclude = [
    # "_NET_WM_WINDOW_TYPE@:a *= 'NOTIFICATION'",
    "window_type *= 'dock'",
    "class_g = 'dmenu'",
    "class_g = 'Tint2'",
    "window_type = 'menu'",
    "window_type = 'tooltip'",
    "window_type = 'popup_menu'",
    "window_type = 'dropdown_menu'"
];

shadow-exclude = [
    "class_i ?= 'riotclientservices.exe'",
    "class_g ?= 'slop'",
    "class_g ?= 'Polybar'",
    "class_g ?= 'Visualizer'",
    # "class_g ?= 'rofi'",
    # i3wm titlebar shadows (tabbed/stacked)
    "class_g ?= 'i3-frame'",
    # i3wm hidden window shadows (tabbed/stacked)
    # "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "_NET_WM_WINDOW_TYPE@:a *= 'SPLASH'",
    # "_NET_WM_WINDOW_TYPE@:a *= 'NOTIFICATION'",
    "window_type *= 'menu'",
    "window_type = 'utility'",
    "window_type = 'dropdown_menu'",
    "window_type = 'popup_menu'"
];
