#! /bin/sh

pkill sxhkd; sxhkd &
pkill polybar; polybar --config=~/.config/polybar/config.ini bar &
pkill picom; picom &
hsetroot -cover ~/Pictures/wallpaper2.png

bspc monitor -d I II III

bspc config border_width         0
bspc config normal_border_color \#32302f
bspc config focused_border_color \#32302f

bspc config window_gap          20

bspc config split_ratio          0.62
bspc config borderless_monocle   true
bspc config gapless_monocle      true
