#!/bin/bash

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 0
berryc title_height       0
berryc edge_gap           64 24 24 24

# Other options
berryc smart_place "true"
berryc edge_lock   "true"
