#!/bin/bash

# Autostart
pkill sxhkd; sxhkd &
pkill picom; picom &
hsetroot -solid '#e5e5ea'
xrdb -load ~/.config/xresources

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 3
berryc title_height       30
berryc top_gap            0

# Set decoration colors
berryc inner_focus_color   1c1c1e
berryc inner_unfocus_color 1c1c1e  
berryc text_focus_color    f2f2f7
berryc text_unfocus_color  aeaeb2

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Satoshi Medium-9"
